if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(_qtrans_mingw_c_compiler gcc)
    set(_qtrans_mingw_cxx_compiler g++)
    set(_qtrans_mingw_rc_compiler windres)
else()
    set(CMAKE_SYSTEM_NAME Windows)
    set(CMAKE_SYSTEM_PROCESSOR x86_64)
    set(_qtrans_mingw_c_compiler x86_64-w64-mingw32-gcc)
    set(_qtrans_mingw_cxx_compiler x86_64-w64-mingw32-g++)
    set(_qtrans_mingw_rc_compiler x86_64-w64-mingw32-windres)
endif()

if(NOT DEFINED CMAKE_C_COMPILER OR CMAKE_C_COMPILER STREQUAL "")
    set(CMAKE_C_COMPILER "${_qtrans_mingw_c_compiler}" CACHE FILEPATH "MinGW C compiler")
endif()

if(NOT DEFINED CMAKE_CXX_COMPILER OR CMAKE_CXX_COMPILER STREQUAL "")
    set(CMAKE_CXX_COMPILER "${_qtrans_mingw_cxx_compiler}" CACHE FILEPATH "MinGW C++ compiler")
endif()

if(NOT DEFINED CMAKE_RC_COMPILER OR CMAKE_RC_COMPILER STREQUAL "")
    set(CMAKE_RC_COMPILER "${_qtrans_mingw_rc_compiler}" CACHE FILEPATH "MinGW resource compiler")
endif()

unset(_qtrans_mingw_c_compiler)
unset(_qtrans_mingw_cxx_compiler)
unset(_qtrans_mingw_rc_compiler)
